### ISSUE TITLE
too difficult to use

### ISSUE THREAD

**Issue by shawnl** [karakanb/sorting-benchmark#1]
please provide a working command line you can pass to the program in README, so that people can quickly proove that your software does something useful before deciding to invest time into it.

**Comment by karakanb** [comment]
Hey, thanks for the feedback. Could you please give an example about what exactly do you expect from the readme? Readme contains a single command to [build the project](https://github.com/karakanb/sorting-benchmark#building-the-project), and it also has a sample command with the [descriptions of all the fields it expects](https://github.com/karakanb/sorting-benchmark#program-arguments). I am not sure what else could there be; since this is a C++ project and the application expects the data in a certain format, there is no easy way to use it without cloning and building the project. 

It has been a while since I have released this project and I haven't worked on it recently; but I am open for suggestions and contributions as well. Feel free to create a PR to improve the readme, I'd be glad to help as well.

**Comment by shawnl** [comment]
I apologize for being rude. I am of course getting the software for free.

Yes, I saw the documentation, but it takes a lot of time to guess what numbers to give those parameters. What I wanted was some sensible defaults that I could just copy and paste into a terminal, and would do a benchmark. Then I could run the in perf and immediately get a feel for the program.

Thank you for your response. I will look at this later today. My goal was in trying to benchmark memcmp, including branch prediction aspects, so I was looking for a program I could easily modify to use memcmp. (I will do that, just letting you know what my goals were.)

**Comment by karakanb** [comment]
Hey, no worries. I get the frustration, it's always hard to know if a project is gonna help you before you put the effort in it. By no means I wanted to imply that you cannot ask anything because this is free or anything, I think you definitely have the rights to ask for a better support for a project, and I'd be glad to help you get going.

If you need quick inputs to try out, you can just clone the repository and get the first few lines from [any of the files in `data/` directory](https://github.com/karakanb/sorting-benchmark/tree/master/data), as far as I remember it was just a number per line, that's it.

Let me know if you need any help. Good luck with your analysis; if you can bring up some analysis results maybe we can even include them in the code, so that the end result would also be demonstrating different aspects as well. Feel free to bring it up here.
